name: Licenses
on: push
jobs:
  check_license_header:
    runs-on: ubuntu-latest
    steps:
      - name: Check License Header
        uses: apache/skywalking-eyes@ed749b83e23f10eae9c379870c3d5ed45ce4e67a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}